Gets correct cluster from datacenter
fog/fog-ovirt pull request #26
Opened 2018-06-05 13:17 UTC by orrabin

This fixes http://projects.theforeman.org/issues/23815

2018-06-19 15:13 UTC, adamruzicka commented on lib/fog/ovirt/requests/compute/v4/create_vm.rb
> +              attrs[:cluster_name] ||= cluster.name
Can there be a situation where `attrs[:cluster]` is unset, but `attrs[:cluster_name]` is set?

2018-06-20 11:25 UTC, orrabin commented on lib/fog/ovirt/requests/compute/v4/create_vm.rb
> +              attrs[:cluster_name] ||= cluster.name
Not that I've seen so far but it's possible if someone calls `create_vm` with the cluster name.
However this should probably change - if there is a name we should search by name and not datacenter and it we searched by datacenter the name should follow.

2018-06-21 12:43 UTC, orrabin commented
@adamruzicka thanks, I changed this to include an option for a provided `cluster_name` with no id.

2018-06-25 08:25 UTC, adamruzicka requested changes
Looks good to me but :policeman: is not happy

2018-06-25 09:34 UTC, orrabin commented
@adamruzicka there were too many lines, I noticed we had an `if` with only 1 statement in it so it was a good opportunity to refactor that as well.

2018-06-27 11:05 UTC, orrabin commented
@adamruzicka rubocop was failing on an unrelated file this time, I'm fixing here but this will causes failures in other PRs as well.

2018-06-27 11:14 UTC, adamruzicka approved these changes

2018-06-27 11:14 UTC, merged

2018-06-27 11:15 UTC, adamruzicka commented
Thanks @orrabin !