Fixes #24564 - Clusters and Vms are shown by selected DC
fog/fog-ovirt pull request #35
Opened 2018-08-13 07:27 UTC by shiramax

2018-08-14 16:24 UTC, ShimShtein requested changes

2018-08-14 16:24 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_clusters.rb
> +            opts[:search] = "datacenter=#{datacenter_hash[:name]}"
If `opts[:search]` already contained some filters, they would be overridden. Is it intentional?

Example:

``` ruby
opts = { search: 'tag = something' }
client.list_clusters(opts)
# => will return all clusters, event without the tag
```

2018-08-14 16:24 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_virtual_machines.rb
> +            filters[:search] += "datacenter=#{datacenter_hash[:name]}"
if I already have `foo=bar` in search field, it will end up with `foo=bardatacenter=bleh`, which is not correct.

2018-08-28 11:34 UTC, shiramax commented
@ShimShtein could you please review again :) ?

2018-08-29 08:56 UTC, ShimShtein requested changes

2018-08-29 08:56 UTC, ShimShtein commented on lib/fog/ovirt/compute/v4.rb
> +            @datacenter_hash ||= (datacenters.select { |x| x[:id] == datacenter })[0] if datacenter
You can use `#find` instead of `select()[0]`.

2018-08-29 08:56 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_clusters.rb
> +            client.system_service.clusters_service.list(opts).map { |ovirt_obj| ovirt_attrs ovirt_obj }
Nitpick: can we put `()` around `ovirt_obj`? `ovirt_attrs(ovirt_obj)` is a bit easier to read.

2018-08-29 08:56 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_clusters.rb
> +            opts[:search] += " datacenter=#{datacenter_hash[:name]}"
This will error if `opts[:search]` is not defined.

2018-08-29 08:56 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_virtual_machines.rb
> +          # rubocop:disable Metrics/AbcSize
Instead of disabling this metric, could we just refactor all `filters` assignments into a private method?

2018-08-29 13:01 UTC, shiramax commented
@ShimShtein let me know if its ok now :)

2018-08-29 18:53 UTC, orrabin commented on lib/fog/ovirt/requests/compute/v4/list_clusters.rb
> +            opts[:search] ||= ""
This is already done in `create_search_by_datacenter`

2018-08-29 19:03 UTC, ShimShtein requested changes
Almost there, a couple of small changes.

2018-08-29 19:03 UTC, ShimShtein commented on lib/fog/ovirt/compute/v4.rb
> +            search += " datacenter=#{datacenter_hash[:name]}"
Nitpick: why not passing datacenter name as a parameter? This way you will not have dependencies on state, only on input parameters.

2018-08-29 19:03 UTC, ShimShtein commented on lib/fog/ovirt/requests/compute/v4/list_clusters.rb
> +            opts[:search] ||= ""
You don't need this anymore.

2018-08-29 19:03 UTC, ShimShtein commented on lib/fog/ovirt/compute/v4.rb
> +          def create_search_by_datacenter(search, page)
If you don't always have values for page or datacenter name, you can make them [named parameters](https://robots.thoughtbot.com/ruby-2-keyword-arguments), or at least put defaults, so you will not have to pass `nil` if you don't have something to put there.

2018-08-30 09:29 UTC, shiramax commented
@ShimShtein thanks! :) should be ready now :)

2018-08-30 13:15 UTC, ShimShtein approved these changes

2018-08-30 13:15 UTC, merged

2018-08-30 13:16 UTC, ShimShtein commented
Merged, thanks @shiramax !