Refs #20394 - Send the volume parameters in template
fog/fog-ovirt pull request #45
Opened 2018-11-20 14:32 UTC by shiramax

2018-12-02 11:19 UTC, orrabin commented on lib/fog/ovirt/requests/compute/v4/list_template_volumes.rb
> +              attachment_disk.storage_domain = attachment_disk.storage_domains[0].id
This is probably not possible but I would suggest checking there is something in storage_domains before trying to take the first one.

2018-12-02 11:26 UTC, orrabin requested changes
Works well, I have 1 nitpick, after that this can be merged.

2018-12-03 08:14 UTC, shiramax commented
Thanks @orrabin , please review again :)

2018-12-03 09:04 UTC, orrabin approved these changes
The UI now shows the storage domain of the disk + the first on the list.
This is consistent with v3 that has the same bug. It's fixed after save and it's an issue in foreman UI.

2018-12-03 09:04 UTC, merged

2018-12-03 09:04 UTC, orrabin commented
Thanks @shiramax !