Fixes #29716 - fix  deprecation warning
fog/fog-ovirt pull request #91
Opened 2020-05-07 06:45 UTC by shiramax

2020-05-07 08:00 UTC, ShimShtein requested changes

2020-05-07 08:00 UTC, ShimShtein commented on lib/fog/ovirt/compute/v4.rb
> +              if value.class.respond_to?(:module_parent) && value.class.module_parent == OvirtSDK4
Not the intention of this PR, but you can use `try`
```suggestion
              value.class.try(:module_parent) == OvirtSDK4
```

2020-05-07 08:12 UTC, ShimShtein approved these changes

2020-05-07 08:14 UTC, ShimShtein requested changes
Sorry, you still need the if statement, my bad

2020-05-07 08:14 UTC, ShimShtein commented on lib/fog/ovirt/compute/v4.rb
> +              value.class.try(:module_parent) == OvirtSDK4
```suggestion
              if value.class.try(:module_parent) == OvirtSDK4
```

2020-05-11 17:05 UTC, ShimShtein commented
Apparently `try` is rails thing. No support for that in pure ruby. Sorry for misleading.

2020-05-12 12:00 UTC, ShimShtein approved these changes
ACK, @orrabin, I see the failures are related to Rubocop in ruby 2.4, and not entirely related to this PR. Do we want to merge this PR regardless rubocop failures?

2020-05-12 12:08 UTC, orrabin commented
I would go with either a PR to fix the rubocop errors first or disabling them if we don't want these cops.

2020-05-24 18:41 UTC, ShimShtein commented
ACK. This makes sense

2020-05-25 13:01 UTC, merged

2020-05-25 13:02 UTC, ShimShtein commented
Merged, thanks @shiramax!